services:
  - type: web
    name: limitless
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NITRO_PRESET
        value: node-server
